fire("ADDON_LOADED","Hourstone"); fire("PLAYER_ENTERING_WORLD",true,false)
fire("TIME_PLAYED_MSG",1125000,200)
local U,db=H.UI,HourstoneDB
SlashCmdList.HOURSTONE("")
assert(U.frame:IsShown() and UISpecialFrames[1]=="HourstoneWindow")
assert(U.total:GetText()==H.M.Format(1125000,"combined"))
U:SetFormat("hours"); assert(db.settings.format=="hours")
assert(U.rows[1].name:GetText()==IDENTITY.name and U.rows[1].active:IsShown())
U:RowTooltip(U.rows[1]); assert(#GameTooltip.lines>=4)
for i=1,140 do
    db.characters["other:"..i]={name=string.rep("Long",8)..i,realm="Realm "..(i%15),level=i%91,seconds=i*1000,class="WARRIOR",updatedAt=EPOCH-i}
end
U:Refresh(); assert(U.maxOffset==133)
U:Scroll(999); assert(U.offset==133 and U.rows[8].entry)
U:ToggleRealms(); assert(#U.realmChoices==17 and U.menu:IsShown())
U.menu.scripts.OnMouseWheel(U.menu,-8); assert(U.realmOffset==11)
local realm=U.realmRows[6].realm; U.realmRows[6].scripts.OnClick(U.realmRows[6])
assert(U.realm==realm and not U.menu:IsShown() and U.offset==0)
U.search:SetText("no match []"); assert(U.empty:IsShown() and not U.rows[1]:IsShown())
U.search:SetText(""); U.realm=nil; U:Refresh()
U.headers.name.button.scripts.OnClick(); assert(U.sortMenu:IsShown())
U.sortRows.name.scripts.OnClick(); assert(U.sort=="name" and not U.descending)
U.sortRows.name.scripts.OnClick(); assert(U.descending)
U.sortRows.level.scripts.OnClick(); assert(U.sort=="level" and U.descending)
U.sortRows.realm.scripts.OnClick(); assert(U.sort=="realm" and not U.descending)
U.headers.updatedAt.button.scripts.OnClick(); assert(U.sort=="updatedAt" and U.descending)
U.headers.seconds.button.scripts.OnClick(); assert(U.sort=="seconds" and U.descending)
U:ToggleSettings(); assert(U.settings:IsShown())
assert(U.minimapBox.kind=="CheckButton" and U.minimapBox.template=="UICheckButtonTemplate")
assert(U.minimapBox:GetChecked())
U.minimapBox:Click(); assert(not db.settings.minimap and not U.minimap:IsShown() and not U.minimapBox:GetChecked())
U.minimapBox:Click(); assert(db.settings.minimap and U.minimap:IsShown() and U.minimapBox:GetChecked())
U.minimapToggle.scripts.OnClick(); assert(not db.settings.minimap and not U.minimap:IsShown())
assert(not U.minimapBox:GetChecked())
SlashCmdList.HOURSTONE("minimap"); assert(U.minimap:IsShown() and U.minimapBox:GetChecked())
assert(U.densityToggle==nil and U.densityMenu==nil and #U.rows==8)
for _,legacy in ipairs({false,true}) do
    db.settings.compact=legacy; U:LayoutRows()
    assert(U.frame:GetHeight()==500 and U.rows[1]:GetHeight()==36 and db.settings.compact==legacy)
end
assert(U.frame:GetHeight()==500 and U.rows[1]:GetHeight()==36)
local before=db.characters
U.scaleSlider:SetValue(90); assert(math.abs(db.settings.scale-.9)<.001)
U.scaleSlider:SetValue(130); assert(db.settings.scale==1.3 and db.characters==before)
configure_display(800,600); U:ApplyScale(); assert(U.frame:GetEffectiveScale()*600/768<=780/720+.0001)
U.search.scripts.OnEscapePressed(U.search); assert(not U.frame:IsShown())
SlashCmdList.HOURSTONE(""); assert(U.frame:IsShown())
fire("UI_SCALE_CHANGED"); fire("DISPLAY_SIZE_CHANGED")
U.frame.scripts.OnHide(); assert(not U.settings:IsShown())
assert(SLASH_HOURSTONE1=="/hourstone" and SLASH_HOURSTONE2=="/azerothhours")
U.minimap.scripts.OnClick(); assert(not U.frame:IsShown())
U.minimap.scripts.OnDragStart(); U.minimap.scripts.OnUpdate()
U.minimap.scripts.OnDragStop(); assert(db.settings.minimapAngle>=0 and db.settings.minimapAngle<360)
U.minimap.scripts.OnClick(); assert(not U.frame:IsShown())
advance(1); U.minimap.scripts.OnClick(); assert(U.frame:IsShown())
