fire("ADDON_LOADED","Hourstone"); fire("PLAYER_ENTERING_WORLD",true,false)
fire("TIME_PLAYED_MSG",1125000,200)
local U,db=H.UI,HourstoneDB
SlashCmdList.HOURSTONE("")
assert(U.frame:IsShown() and UISpecialFrames[1]=="HourstoneWindow")
assert(U.total:GetText()==H.M.Format(1125000,"combined"))
U:SetFormat("hours"); assert(db.settings.format=="hours")
assert(U.rows[1].name:GetText()==IDENTITY.name and U.rows[1].active:IsShown())
U:RowTooltip(U.rows[1]); assert(#GameTooltip.lines>=4)
for i=1,140 do
    db.characters["other:"..i]={name=string.rep("Long",8)..i,realm="Realm "..(i%15),level=i%91,seconds=i*1000,class="WARRIOR",updatedAt=EPOCH-i}
end
U:Refresh(); assert(U.maxOffset==133)
U:Scroll(999); assert(U.offset==133 and U.rows[8].entry)
U:ToggleRealms(); assert(#U.realmChoices==17 and U.menu:IsShown())
U.menu.scripts.OnMouseWheel(U.menu,-8); assert(U.realmOffset==9)
local realm=U.realmRows[8].realm; U.realmRows[8].scripts.OnClick(U.realmRows[8])
assert(U.realm==realm and not U.menu:IsShown() and U.offset==0)
U.search:SetText("no match []"); assert(U.empty:IsShown() and not U.rows[1]:IsShown())
U.search:SetText(""); U.realm=nil; U:Refresh()
U.headers.name.button.scripts.OnClick(); assert(U.sort=="name" and not U.descending)
U.headers.name.button.scripts.OnClick(); assert(U.descending)
U:ToggleSettings(); assert(U.settings:IsShown())
U.minimapToggle.scripts.OnClick(); assert(not db.settings.minimap and not U.minimap:IsShown())
SlashCmdList.HOURSTONE("minimap"); assert(U.minimap:IsShown())
U.densityToggle.scripts.OnClick(); assert(db.settings.compact and U.rows[10]:IsShown())
db.settings.scale=1.3; UIParent:SetSize(1024,768); U:ApplyScale(); assert(U.frame:GetScale()<=1024/960)
U.search.scripts.OnEscapePressed(U.search); assert(not U.frame:IsShown())
SlashCmdList.HOURSTONE(""); assert(U.frame:IsShown())
fire("UI_SCALE_CHANGED"); fire("DISPLAY_SIZE_CHANGED")
U.frame.scripts.OnHide(); assert(not U.settings:IsShown())
assert(SLASH_HOURSTONE1=="/hourstone" and SLASH_HOURSTONE2=="/azerothhours")
U.minimap.scripts.OnClick(); assert(not U.frame:IsShown())
U.minimap.scripts.OnDragStart(); U.minimap.scripts.OnUpdate()
U.minimap.scripts.OnDragStop(); assert(db.settings.minimapAngle>=0 and db.settings.minimapAngle<360)
U.minimap.scripts.OnClick(); assert(not U.frame:IsShown())
advance(1); U.minimap.scripts.OnClick(); assert(U.frame:IsShown())
